### PR TITLE
Fix CI and much more for Django 2.2 & 3.0 support

### PR DESCRIPTION
**Pull request by joehybird**

### CODE REVIEW

**Comment by joehybird** [comment]
You can see CI build here https://travis-ci.com/joehybird/django-el-pagination/builds/147217383 (seems disabled on your repository).

**Comment by shtalinberg** [comment]
I will merge these changes, I see a little issue in my build https://travis-ci.org/shtalinberg/django-el-pagination/builds/645495523

**Comment by joehybird** [comment]
@shtalinberg Yes, integration may randomly fail (and the CI config expects it) depending of the execution delays.
This caused by a little change to speed up tests in the waiting delay for `WebDriverWait` : 5 secs instead of 10 (see https://github.com/shtalinberg/django-el-pagination/blob/fd0666f707823732fe510bb7393e0d336283e75b/el_pagination/tests/integration/__init__.py#L37)

**Comment by joehybird** [comment]
Oh, I forgot, a release soon will be great ! :smile:

**Pull request merged**
